-- ====================================================================
-- RESET & INIT DATABASE SCRIPT (Làm mới hoàn toàn Database)
-- ====================================================================
-- CẢNH BÁO: Script này sẽ XÓA TOÀN BỘ dữ liệu hiện có và tạo lại cấu trúc bảng trắng.
-- Hãy chắc chắn bạn đã backup dữ liệu hoặc thực sự muốn làm mới hệ thống.
-- ====================================================================

-- 1. XÓA BẢNG CŨ (DROP TABLES) & EXTENSIONS
-- ====================================================================
DROP TABLE IF EXISTS daily_logs CASCADE;

DROP TABLE IF EXISTS repair_history CASCADE;

DROP TABLE IF EXISTS maintenance_history CASCADE;

DROP TABLE IF EXISTS maintenance_standards CASCADE;

DROP TABLE IF EXISTS maintenance_supplies CASCADE;

DROP TABLE IF EXISTS report_snapshots CASCADE;

DROP TABLE IF EXISTS notifications CASCADE;

DROP TABLE IF EXISTS machines CASCADE;

DROP TABLE IF EXISTS parts CASCADE;

DROP TABLE IF EXISTS error_codes CASCADE;

DROP TABLE IF EXISTS projects CASCADE;

DROP TABLE IF EXISTS users CASCADE;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TẠO BẢNG CHÍNH (CORE TABLES)
-- ====================================================================

-- [PROJECTS] - Các dự án / Công trường
CREATE TABLE projects (
    id SERIAL PRIMARY KEY,
    code text,
    name text NOT NULL,
    address text,
    start_date date,
    end_date date,
    status text DEFAULT 'active', -- active, paused, completed
    description text,
    created_at timestamptz DEFAULT now()
);

-- [USERS] - Người dùng hệ thống
CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text UNIQUE NOT NULL,
    password text NOT NULL, -- Lưu ý: Nên mã hóa password trong thực tế
    name text NOT NULL,
    role text NOT NULL DEFAULT 'technician', -- super_admin, project_admin, site_manager, technician
    department text,
    assigned_projects jsonb DEFAULT '[]'::jsonb,
    created_at timestamptz DEFAULT now()
);

-- [MACHINES] - Danh sách xe / máy
CREATE TABLE machines (
    id uuid DEFAULT uuid_generate_v4 () PRIMARY KEY,
    code text NOT NULL UNIQUE, -- Mã tài sản (Unique)
    name text,
    model text,
    serial_number text,
    department text, -- Added from clone_app
    status text CHECK (
        status IN (
            'active',
            'maintenance',
            'broken',
            'disposed'
        )
    ) DEFAULT 'active',
    current_hours numeric DEFAULT 0,
    current_km numeric DEFAULT 0,
    project_id bigint REFERENCES projects (id) ON DELETE SET NULL,
    project_name text, -- Lưu tên dự án (cache) để tiện truy vấn
    description text,

-- Maintenance tracking (Added from clone_app)
next_maintenance_hours numeric,
    next_maintenance_km numeric,
    maintenance_interval numeric DEFAULT 500,
    last_maintenance_date date,
    last_maintenance_hours numeric,

    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- [MAINTENANCE STANDARDS] - Định mức bảo dưỡng
CREATE TABLE maintenance_standards (
    id uuid DEFAULT uuid_generate_v4 () PRIMARY KEY,
    model_ref text, -- Áp dụng cho Model xe nào (hoặc Code cụ thể)
    machine_code text, -- Hoặc áp dụng cho mã xe cụ thể
    machine_model text, -- Thay thế dần model_ref
    interval_hours numeric NOT NULL, -- Chu kỳ bảo dưỡng (ví dụ: 500h)
    part_name text NOT NULL, -- Tên phụ tùng cần thay (ví dụ: Lọc nhớt)
    note text,
    created_at timestamptz DEFAULT now()
);

-- [parts] & [error_codes] - Danh mục phụ
CREATE TABLE parts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number text UNIQUE NOT NULL,
    name text,
    equivalents text,
    created_at timestamptz DEFAULT now()
);

CREATE TABLE error_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text UNIQUE NOT NULL,
    description text,
    fix_steps text,
    created_at timestamptz DEFAULT now()
);

-- [MAINTENANCE SUPPLIES] - Vật tư bảo dưỡng (Added from clone_app)
CREATE TABLE maintenance_supplies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code text,
    "group" text,
    name text,
    code text,
    unit text,
    quantity numeric DEFAULT 1,
    donaldson_code text,
    maintenance_interval numeric,
    created_at timestamptz DEFAULT now()
);

-- [REPORT SNAPSHOTS] - Lưu trữ báo cáo (Added from clone_app)
CREATE TABLE report_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date,
    stats jsonb,
    created_at timestamptz DEFAULT now()
);

-- 3. TẠO BẢNG HOẠT ĐỘNG (OPERATIONAL TABLES)
-- ====================================================================

-- [DAILY LOGS] - Nhật trình hoạt động hàng ngày
CREATE TABLE daily_logs (
    id uuid DEFAULT uuid_generate_v4 () PRIMARY KEY,
    machine_id uuid REFERENCES machines (id) ON DELETE CASCADE,
    machine_code text, -- Lưu cache mã xe
    date date DEFAULT current_date NOT NULL,
    hours_added numeric NOT NULL CHECK (hours_added >= 0),
    odo_km numeric DEFAULT 0,
    fuel_consumed numeric DEFAULT 0,

-- Maintenance specific logs (Added from clone_app)
maintenance_done boolean DEFAULT false,
    maintenance_description text,

    note text,
    created_at timestamptz DEFAULT now()
);

-- [MAINTENANCE HISTORY] - Lịch sử bảo dưỡng (Nhập từ file Excel của bạn)
CREATE TABLE maintenance_history (
    id uuid DEFAULT uuid_generate_v4 () PRIMARY KEY,
    machine_id uuid REFERENCES machines (id) ON DELETE SET NULL, -- Có thể null nếu import xe chưa có trong hệ thống
    machine_code text,
    date date DEFAULT current_date,
    task_name text, -- Nội dung công việc
    performer text, -- Người thực hiện
    hours_at_maintenance numeric, -- Số giờ máy tại thời điểm BD
    km_at_maintenance numeric,
    cost numeric DEFAULT 0,
    notes text,
    maintenance_level text,
    created_at timestamptz DEFAULT now()
);

-- [REPAIR HISTORY] - Lịch sử sửa chữa phát sinh
CREATE TABLE repair_history (
    id uuid DEFAULT uuid_generate_v4 () PRIMARY KEY,
    machine_id uuid REFERENCES machines (id) ON DELETE CASCADE,
    machine_code text,
    date date DEFAULT current_date,
    issue text, -- Vấn đề / Sự cố
    cause text, -- Nguyên nhân
    description text, -- Mô tả chi tiết
    cost numeric DEFAULT 0,
    parts_ordered_date date,
    parts_arrived_date date,
    completed_date date,
    status text DEFAULT 'pending', -- pending, in_progress, completed
    source text DEFAULT 'manual',
    external_id text,
    created_at timestamptz DEFAULT now()
);

-- [NOTIFICATIONS]
CREATE TABLE notifications (
    id uuid DEFAULT uuid_generate_v4 () PRIMARY KEY,
    project_name text,
    title text NOT NULL,
    message text,
    type text CHECK (
        type IN (
            'info',
            'warning',
            'error',
            'success'
        )
    ) DEFAULT 'info',
    is_read boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

-- 4. TẠO INDEX (Tối ưu truy vấn)
-- ====================================================================
CREATE INDEX idx_machines_code ON machines (code);

CREATE INDEX idx_machines_project_id ON machines (project_id);

CREATE INDEX idx_daily_logs_machine_id ON daily_logs (machine_id);

CREATE INDEX idx_daily_logs_date ON daily_logs (date);

CREATE INDEX idx_maintenance_history_machine_code ON maintenance_history (machine_code);

CREATE INDEX idx_maintenance_history_date ON maintenance_history (date);

-- 5. BẬT RLS (ROW LEVEL SECURITY) - Cho phép mọi người truy cập (Demo mode)
-- ====================================================================
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

ALTER TABLE users ENABLE ROW LEVEL SECURITY;

ALTER TABLE machines ENABLE ROW LEVEL SECURITY;

ALTER TABLE daily_logs ENABLE ROW LEVEL SECURITY;

ALTER TABLE maintenance_history ENABLE ROW LEVEL SECURITY;

ALTER TABLE repair_history ENABLE ROW LEVEL SECURITY;

ALTER TABLE maintenance_supplies ENABLE ROW LEVEL SECURITY;

ALTER TABLE report_snapshots ENABLE ROW LEVEL SECURITY;

-- Tạo policy mở cho tất cả (để tránh lỗi permission denied khi mới chạy)
CREATE POLICY "Public Access Projects" ON projects FOR ALL USING (true)
WITH
    CHECK (true);

CREATE POLICY "Public Access Users" ON users FOR ALL USING (true)
WITH
    CHECK (true);

CREATE POLICY "Public Access Machines" ON machines FOR ALL USING (true)
WITH
    CHECK (true);

CREATE POLICY "Public Access DailyLogs" ON daily_logs FOR ALL USING (true)
WITH
    CHECK (true);

CREATE POLICY "Public Access Maintenance" ON maintenance_history FOR ALL USING (true)
WITH
    CHECK (true);

CREATE POLICY "Public Access Repairs" ON repair_history FOR ALL USING (true)
WITH
    CHECK (true);

CREATE POLICY "Public Access MaintSupplies" ON maintenance_supplies FOR ALL USING (true)
WITH
    CHECK (true);

CREATE POLICY "Public Access Snapshots" ON report_snapshots FOR ALL USING (true)
WITH
    CHECK (true);

-- 6. TẠO TRIGGER TỰ ĐỘNG CẬP NHẬT GIỜ MÁY
-- ====================================================================
CREATE OR REPLACE FUNCTION update_machine_hours()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.machine_id IS NOT NULL THEN
        UPDATE machines
        SET current_hours = current_hours + NEW.hours_added,
            updated_at = NOW()
        WHERE id = NEW.machine_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_hours
AFTER INSERT ON daily_logs
FOR EACH ROW
EXECUTE FUNCTION update_machine_hours();

-- 7. KHỞI TẠO DỮ LIỆU MẪU (SEED DATA)
-- ====================================================================
-- Tài khoản Admin mặc định
INSERT INTO
    users (
        username,
        password,
        name,
        role
    )
VALUES (
        'admin',
        'admin123',
        'Administrator',
        'super_admin'
    );

-- Seed Error Codes (From clone_app)
INSERT INTO
    error_codes (code, description, fix_steps)
VALUES (
        'E001',
        'Cảm biến nhiệt độ nước làm mát quá cao. Kiểm tra két nước và quạt làm mát.',
        '1. Kiểm tra mức nước làm mát.\n2. Kiểm tra quạt gió.\n3. Thay thế cảm biến nếu cần.'
    ),
    (
        'P0300',
        'Phát hiện bỏ máy ngẫu nhiên. Kiểm tra bugi, mobin đánh lửa.',
        '1. Tháo và kiểm tra bugi.\n2. Kiểm tra áp suất nén.'
    ),
    (
        'C1201',
        'Lỗi hệ thống kiểm soát phanh. Kiểm tra cảm biến ABS.',
        '1. Kiểm tra dây dẫn cảm biến ABS.\n2. Vệ sinh mắt đọc.'
    );

-- Seed Parts (From clone_app)
INSERT INTO
    parts (
        part_number,
        name,
        equivalents
    )
VALUES (
        'LF9009',
        'Lọc nhớt Fleetguard',
        'B7085, P553000'
    ),
    (
        'FF5488',
        'Lọc nhiên liệu',
        'P550881'
    ),
    (
        'AH1103',
        'Lọc gió động cơ',
        'SAKURA A-5503'
    );

-- Dự án mẫu (Optional)
INSERT INTO
    projects (name, code, start_date)
VALUES (
        'Dự án Tổng hợp',
        'PROJ-001',
        '2024-01-01'
    );